export const EMPLOYEE_LIST_REQUEST = 'EMPLOYEE_LIST_REQUEST'
export const EMPLOYEE_LIST_SUCCESS = 'EMPLOYEE_LIST_SUCCESS'
export const EMPLOYEE_LIST_FAILS = 'EMPLOYEE_LIST_FAILS'

export const EMPLOYEE_LOGIN_REQUEST = 'EMPLOYEE_LOGIN_REQUEST'
export const EMPLOYEE_LOGIN_FAILS = 'EMPLOYEE_LOGIN_FAILS'
export const EMPLOYEE_LOGIN_SUCCESS = 'EMPLOYEE_LOGIN_SUCCESS'
export const EMPLOYEE_LOGOUT = 'EMPLOYEE_LOGOUT'