export const TODAY_MENU_REQUEST = 'TODAY_MENU_REQUEST'
export const TODAY_MENU_FAILS = 'TODAY_MENU_FAILS'
export const TODAY_MENU_SUCCESS = 'TODAY_MENU_SUCCESS'

export const PLATES_LIST_REQUEST = 'PLATES_LIST_REQUEST'
export const PLATES_LIST_SUCCESS = 'PLATES_LIST_SUCCESS'
export const PLATES_LIST_FAILS = 'PLATES_LIST_FAILS'
export const PLATES_LIST_RESET = 'PLATES_LIST_RESET'

export const PLATE_CREATE_REQUEST = 'PLATE_CREATE_REQUEST'
export const PLATE_CREATE_SUCCESS = 'PLATE_CREATE_SUCCESS'
export const PLATE_CREATE_FAILS = 'PLATE_CREATE_FAILS'
export const PLATE_CREATE_RESET = 'PLATE_CREATE_RESET'

export const CREATE_MENU_REQUEST = 'CREATE_MENU_REQUEST'
export const CREATE_MENU_SUCCESS = 'CREATE_MENU_SUCCESS'
export const CREATE_MENU_FAILS = 'CREATE_MENU_FAILS'
export const CREATE_MENU_RESET = 'CREATE_MENU_RESET'

export const CREATE_EMPLOYEE_SELECTION_REQUEST = 'CREATE_EMPLOYEE_SELECTION_REQUEST'
export const CREATE_EMPLOYEE_SELECTION_SUCCESS = 'CREATE_EMPLOYEE_SELECTION_SUCCESS'
export const CREATE_EMPLOYEE_SELECTION_FAILS = 'CREATE_EMPLOYEE_SELECTION_FAILS'
