# Generated by Django 4.0.1 on 2022-01-29 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_rename_date_employeeselection_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='date',
            new_name='day',
        ),
    ]
