# Generated by Django 4.0.1 on 2022-01-30 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0003_rename_date_menu_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='day',
            field=models.DateField(unique=True),
        ),
    ]
