# Generated by Django 4.0.1 on 2022-01-30 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0004_alter_menu_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeselection',
            name='day',
        ),
        migrations.AddField(
            model_name='employeeselection',
            name='menu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='menus.menu'),
            preserve_default=False,
        ),
    ]
