# Generated by Django 4.0.1 on 2022-02-01 19:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menus', '0006_alter_plate_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employeeselection',
            unique_together={('employee', 'menu')},
        ),
    ]
